name: shartflix
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get_it: ^8.0.3
  flutter_bloc: ^9.1.1
  go_router: ^16.0.0
  dio: ^5.8.0+1
  flutter_secure_storage: ^9.2.4
  flutter_screenutil: ^5.9.3
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  equatable: ^2.0.7
  flutter_inset_shadow: ^2.0.3
  top_snackbar_flutter: ^3.3.0
  flutter_native_splash: ^2.4.6
  lottie: ^3.3.1
  firebase_core: ^3.15.2
  firebase_crashlytics: ^4.3.10
  firebase_analytics: ^11.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:

  uses-material-design: true

  fonts:
    - family: EuclidCircularA
      fonts:
        - asset: assets/fonts/Euclid Circular A Regular.ttf
          weight: 400
        - asset: assets/fonts/Euclid Circular A Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Euclid Circular A Light.ttf
          weight: 300
        - asset: assets/fonts/Euclid Circular A Light Italic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Euclid Circular A Medium.ttf
          weight: 500
        - asset: assets/fonts/Euclid Circular A Medium Italic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Euclid Circular A SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Euclid Circular A SemiBold Italic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Euclid Circular A Bold.ttf
          weight: 700
        - asset: assets/fonts/Euclid Circular A Bold Italic.ttf
          weight: 700
          style: italic

  assets:
    - assets/images/
    - assets/localization/
    - assets/icons/
    - assets/icons/paywall/
    - assets/animations/